export const productData = [
  {
    name: "Bento",
    expiration_date: "2022-12-05",
    price: 300,
    original_price: 500,
    imageUrl: "https://picsum.photos/400/300",
    shop: "Fuji Store",
    type: "ready to eat",
  },
  {
    name: "Sandwhich",
    expiration_date: "2022-10-10",
    price: 250,
    original_price: 600,
    imageUrl: "https://picsum.photos/400/300",
    shop: "Meguro Market",
    type: "ready to eat",
  },
  {
    name: "Melon Pan",
    expiration_date: "2023-01-10",
    price: 110,
    original_price: 200,
    imageUrl: "https://picsum.photos/400/300",
    shop: "Tokyo Supreme",
    type: "ready to eat",
  },
  {
    name: "Tofu",
    expiration_date: "2022-10-10",
    price: 50,
    original_price: 100,
    imageUrl: "https://picsum.photos/400/300",
    shop: "Tokyo Supreme",
    type: "misc",
  },
  {
    name: "Karaage",
    expiration_date: "2022-10-10",
    price: 140,
    original_price: 320,
    imageUrl: "https://picsum.photos/400/300",
    shop: "CC Shop",
    type: "poultry",
  },
];
